version: '3'
services:
  homeassistant:
    container_name: home-assistant
    restart: unless-stopped
    image: homeassistant/raspberrypi3-homeassistant
    volumes:
      - /srv/docker/HomeAssistantConfig:/config
      - /etc/localtime:/etc/localtime:ro
      # - /srv/docker/hass_media:/media
    network_mode: host
    privileged: true
    depends_on:
     - mariadb
  mariadb:
    image: jsurf/rpi-mariadb:latest
    ports:
      - 3306:3306/tcp
    volumes:
      - /srv/docker/mariadb/config:/etc/mysql/conf.d
      - /srv/docker/mariadb/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=super_database_password
      - MYSQL_DATABASE=homeassistantdb
      - MYSQL_USER=homeassistant
      - MYSQL_PASSWORD=a_database_password
    restart: always
  nodered:
    image: nodered/node-red-docker:rpi-v8
    ports:
     - "1880:1880"
    volumes:
     - /srv/docker/nodered:/data
    user: "1000"
    restart: always
    environment:
      TZ: "America/New_York"
